//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVEAPIUtility.DocSearchSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVSESSION", Namespace="http://www.digitechsystems.com")]
    [System.SerializableAttribute()]
    public partial class PVSESSION : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SESSIONIDField;
        
        private int ENTITYIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SOURCEIPADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEVELOPERIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SESSIONID {
            get {
                return this.SESSIONIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SESSIONIDField, value) != true)) {
                    this.SESSIONIDField = value;
                    this.RaisePropertyChanged("SESSIONID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ENTITYID {
            get {
                return this.ENTITYIDField;
            }
            set {
                if ((this.ENTITYIDField.Equals(value) != true)) {
                    this.ENTITYIDField = value;
                    this.RaisePropertyChanged("ENTITYID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SOURCEIPADDRESS {
            get {
                return this.SOURCEIPADDRESSField;
            }
            set {
                if ((object.ReferenceEquals(this.SOURCEIPADDRESSField, value) != true)) {
                    this.SOURCEIPADDRESSField = value;
                    this.RaisePropertyChanged("SOURCEIPADDRESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DEVELOPERID {
            get {
                return this.DEVELOPERIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DEVELOPERIDField, value) != true)) {
                    this.DEVELOPERIDField = value;
                    this.RaisePropertyChanged("DEVELOPERID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVQUERY", Namespace="http://www.digitechsystems.com")]
    [System.SerializableAttribute()]
    public partial class PVQUERY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PVEAPIUtility.DocSearchSvc.PVPROJECTQUERY[] PROJECTQUERIESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PVEAPIUtility.DocSearchSvc.PVPROJECTQUERY[] PROJECTQUERIES {
            get {
                return this.PROJECTQUERIESField;
            }
            set {
                if ((object.ReferenceEquals(this.PROJECTQUERIESField, value) != true)) {
                    this.PROJECTQUERIESField = value;
                    this.RaisePropertyChanged("PROJECTQUERIES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVPROJECTQUERY", Namespace="http://www.digitechsystems.com")]
    [System.SerializableAttribute()]
    public partial class PVPROJECTQUERY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CALLERQUERYIDField;
        
        private long PROJECTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PVEAPIUtility.DocSearchSvc.PVFIELD[] FIELDSTORETURNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PVEAPIUtility.DocSearchSvc.PVCONDITION CONDITIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PVEAPIUtility.DocSearchSvc.PVSORT[] SORTFIELDSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PVEAPIUtility.DocSearchSvc.PVFULLTEXTQUERY FULLTEXTQUERYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPILEDQUERYField;
        
        private int PAGESIZEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAGEKEYField;
        
        private bool IGNOREERRORSField;
        
        private bool RETURNCOUNTONLYField;
        
        private bool RETURNSEARCHSTATISICSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CALLERQUERYID {
            get {
                return this.CALLERQUERYIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CALLERQUERYIDField, value) != true)) {
                    this.CALLERQUERYIDField = value;
                    this.RaisePropertyChanged("CALLERQUERYID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long PROJECTID {
            get {
                return this.PROJECTIDField;
            }
            set {
                if ((this.PROJECTIDField.Equals(value) != true)) {
                    this.PROJECTIDField = value;
                    this.RaisePropertyChanged("PROJECTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public PVEAPIUtility.DocSearchSvc.PVFIELD[] FIELDSTORETURN {
            get {
                return this.FIELDSTORETURNField;
            }
            set {
                if ((object.ReferenceEquals(this.FIELDSTORETURNField, value) != true)) {
                    this.FIELDSTORETURNField = value;
                    this.RaisePropertyChanged("FIELDSTORETURN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public PVEAPIUtility.DocSearchSvc.PVCONDITION CONDITION {
            get {
                return this.CONDITIONField;
            }
            set {
                if ((object.ReferenceEquals(this.CONDITIONField, value) != true)) {
                    this.CONDITIONField = value;
                    this.RaisePropertyChanged("CONDITION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public PVEAPIUtility.DocSearchSvc.PVSORT[] SORTFIELDS {
            get {
                return this.SORTFIELDSField;
            }
            set {
                if ((object.ReferenceEquals(this.SORTFIELDSField, value) != true)) {
                    this.SORTFIELDSField = value;
                    this.RaisePropertyChanged("SORTFIELDS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public PVEAPIUtility.DocSearchSvc.PVFULLTEXTQUERY FULLTEXTQUERY {
            get {
                return this.FULLTEXTQUERYField;
            }
            set {
                if ((object.ReferenceEquals(this.FULLTEXTQUERYField, value) != true)) {
                    this.FULLTEXTQUERYField = value;
                    this.RaisePropertyChanged("FULLTEXTQUERY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string COMPILEDQUERY {
            get {
                return this.COMPILEDQUERYField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPILEDQUERYField, value) != true)) {
                    this.COMPILEDQUERYField = value;
                    this.RaisePropertyChanged("COMPILEDQUERY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int PAGESIZE {
            get {
                return this.PAGESIZEField;
            }
            set {
                if ((this.PAGESIZEField.Equals(value) != true)) {
                    this.PAGESIZEField = value;
                    this.RaisePropertyChanged("PAGESIZE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PAGEKEY {
            get {
                return this.PAGEKEYField;
            }
            set {
                if ((object.ReferenceEquals(this.PAGEKEYField, value) != true)) {
                    this.PAGEKEYField = value;
                    this.RaisePropertyChanged("PAGEKEY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool IGNOREERRORS {
            get {
                return this.IGNOREERRORSField;
            }
            set {
                if ((this.IGNOREERRORSField.Equals(value) != true)) {
                    this.IGNOREERRORSField = value;
                    this.RaisePropertyChanged("IGNOREERRORS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool RETURNCOUNTONLY {
            get {
                return this.RETURNCOUNTONLYField;
            }
            set {
                if ((this.RETURNCOUNTONLYField.Equals(value) != true)) {
                    this.RETURNCOUNTONLYField = value;
                    this.RaisePropertyChanged("RETURNCOUNTONLY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool RETURNSEARCHSTATISICS {
            get {
                return this.RETURNSEARCHSTATISICSField;
            }
            set {
                if ((this.RETURNSEARCHSTATISICSField.Equals(value) != true)) {
                    this.RETURNSEARCHSTATISICSField = value;
                    this.RaisePropertyChanged("RETURNSEARCHSTATISICS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVCONDITION", Namespace="http://www.digitechsystems.com")]
    [System.SerializableAttribute()]
    public partial class PVCONDITION : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIELDNAMEField;
        
        private PVEAPIUtility.DocSearchSvc.PVOPERATOR OPERATORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QUERYVALUEField;
        
        private bool CONDITIONGROUPField;
        
        private PVEAPIUtility.DocSearchSvc.PVBOOLEAN CONDITIONCONNECTORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PVEAPIUtility.DocSearchSvc.PVCONDITION[] CONDITIONSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FIELDNAME {
            get {
                return this.FIELDNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FIELDNAMEField, value) != true)) {
                    this.FIELDNAMEField = value;
                    this.RaisePropertyChanged("FIELDNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public PVEAPIUtility.DocSearchSvc.PVOPERATOR OPERATOR {
            get {
                return this.OPERATORField;
            }
            set {
                if ((this.OPERATORField.Equals(value) != true)) {
                    this.OPERATORField = value;
                    this.RaisePropertyChanged("OPERATOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string QUERYVALUE {
            get {
                return this.QUERYVALUEField;
            }
            set {
                if ((object.ReferenceEquals(this.QUERYVALUEField, value) != true)) {
                    this.QUERYVALUEField = value;
                    this.RaisePropertyChanged("QUERYVALUE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool CONDITIONGROUP {
            get {
                return this.CONDITIONGROUPField;
            }
            set {
                if ((this.CONDITIONGROUPField.Equals(value) != true)) {
                    this.CONDITIONGROUPField = value;
                    this.RaisePropertyChanged("CONDITIONGROUP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public PVEAPIUtility.DocSearchSvc.PVBOOLEAN CONDITIONCONNECTOR {
            get {
                return this.CONDITIONCONNECTORField;
            }
            set {
                if ((this.CONDITIONCONNECTORField.Equals(value) != true)) {
                    this.CONDITIONCONNECTORField = value;
                    this.RaisePropertyChanged("CONDITIONCONNECTOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public PVEAPIUtility.DocSearchSvc.PVCONDITION[] CONDITIONS {
            get {
                return this.CONDITIONSField;
            }
            set {
                if ((object.ReferenceEquals(this.CONDITIONSField, value) != true)) {
                    this.CONDITIONSField = value;
                    this.RaisePropertyChanged("CONDITIONS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVFULLTEXTQUERY", Namespace="http://www.digitechsystems.com")]
    [System.SerializableAttribute()]
    public partial class PVFULLTEXTQUERY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private PVEAPIUtility.DocSearchSvc.PVQUERYTYPE QUERYTYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QUERYVALUEField;
        
        private int FUZZINESSField;
        
        private bool PHONICField;
        
        private bool STEMMINGField;
        
        private bool NATURALLANGUAGEField;
        
        private bool SYNONYMSALLWORDSField;
        
        private bool SYNONYMSUSERField;
        
        private bool SYNONYMSWORDNETField;
        
        private bool SYNONYMSWORDNETRELATEDField;
        
        private bool RETURNTITLEField;
        
        private bool RETURNSTATISTICSField;
        
        private bool QUERYAFTERINDICESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public PVEAPIUtility.DocSearchSvc.PVQUERYTYPE QUERYTYPE {
            get {
                return this.QUERYTYPEField;
            }
            set {
                if ((this.QUERYTYPEField.Equals(value) != true)) {
                    this.QUERYTYPEField = value;
                    this.RaisePropertyChanged("QUERYTYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string QUERYVALUE {
            get {
                return this.QUERYVALUEField;
            }
            set {
                if ((object.ReferenceEquals(this.QUERYVALUEField, value) != true)) {
                    this.QUERYVALUEField = value;
                    this.RaisePropertyChanged("QUERYVALUE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int FUZZINESS {
            get {
                return this.FUZZINESSField;
            }
            set {
                if ((this.FUZZINESSField.Equals(value) != true)) {
                    this.FUZZINESSField = value;
                    this.RaisePropertyChanged("FUZZINESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool PHONIC {
            get {
                return this.PHONICField;
            }
            set {
                if ((this.PHONICField.Equals(value) != true)) {
                    this.PHONICField = value;
                    this.RaisePropertyChanged("PHONIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool STEMMING {
            get {
                return this.STEMMINGField;
            }
            set {
                if ((this.STEMMINGField.Equals(value) != true)) {
                    this.STEMMINGField = value;
                    this.RaisePropertyChanged("STEMMING");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool NATURALLANGUAGE {
            get {
                return this.NATURALLANGUAGEField;
            }
            set {
                if ((this.NATURALLANGUAGEField.Equals(value) != true)) {
                    this.NATURALLANGUAGEField = value;
                    this.RaisePropertyChanged("NATURALLANGUAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool SYNONYMSALLWORDS {
            get {
                return this.SYNONYMSALLWORDSField;
            }
            set {
                if ((this.SYNONYMSALLWORDSField.Equals(value) != true)) {
                    this.SYNONYMSALLWORDSField = value;
                    this.RaisePropertyChanged("SYNONYMSALLWORDS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool SYNONYMSUSER {
            get {
                return this.SYNONYMSUSERField;
            }
            set {
                if ((this.SYNONYMSUSERField.Equals(value) != true)) {
                    this.SYNONYMSUSERField = value;
                    this.RaisePropertyChanged("SYNONYMSUSER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool SYNONYMSWORDNET {
            get {
                return this.SYNONYMSWORDNETField;
            }
            set {
                if ((this.SYNONYMSWORDNETField.Equals(value) != true)) {
                    this.SYNONYMSWORDNETField = value;
                    this.RaisePropertyChanged("SYNONYMSWORDNET");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool SYNONYMSWORDNETRELATED {
            get {
                return this.SYNONYMSWORDNETRELATEDField;
            }
            set {
                if ((this.SYNONYMSWORDNETRELATEDField.Equals(value) != true)) {
                    this.SYNONYMSWORDNETRELATEDField = value;
                    this.RaisePropertyChanged("SYNONYMSWORDNETRELATED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool RETURNTITLE {
            get {
                return this.RETURNTITLEField;
            }
            set {
                if ((this.RETURNTITLEField.Equals(value) != true)) {
                    this.RETURNTITLEField = value;
                    this.RaisePropertyChanged("RETURNTITLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool RETURNSTATISTICS {
            get {
                return this.RETURNSTATISTICSField;
            }
            set {
                if ((this.RETURNSTATISTICSField.Equals(value) != true)) {
                    this.RETURNSTATISTICSField = value;
                    this.RaisePropertyChanged("RETURNSTATISTICS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool QUERYAFTERINDICES {
            get {
                return this.QUERYAFTERINDICESField;
            }
            set {
                if ((this.QUERYAFTERINDICESField.Equals(value) != true)) {
                    this.QUERYAFTERINDICESField = value;
                    this.RaisePropertyChanged("QUERYAFTERINDICES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVFIELD", Namespace="http://www.digitechsystems.com")]
    [System.SerializableAttribute()]
    public partial class PVFIELD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIELDNAMEField;
        
        private bool HASHField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FIELDNAME {
            get {
                return this.FIELDNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FIELDNAMEField, value) != true)) {
                    this.FIELDNAMEField = value;
                    this.RaisePropertyChanged("FIELDNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool HASH {
            get {
                return this.HASHField;
            }
            set {
                if ((this.HASHField.Equals(value) != true)) {
                    this.HASHField = value;
                    this.RaisePropertyChanged("HASH");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVSORT", Namespace="http://www.digitechsystems.com")]
    [System.SerializableAttribute()]
    public partial class PVSORT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIELDNAMEField;
        
        private PVEAPIUtility.DocSearchSvc.PVSORTORDER SORTORDERField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FIELDNAME {
            get {
                return this.FIELDNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FIELDNAMEField, value) != true)) {
                    this.FIELDNAMEField = value;
                    this.RaisePropertyChanged("FIELDNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public PVEAPIUtility.DocSearchSvc.PVSORTORDER SORTORDER {
            get {
                return this.SORTORDERField;
            }
            set {
                if ((this.SORTORDERField.Equals(value) != true)) {
                    this.SORTORDERField = value;
                    this.RaisePropertyChanged("SORTORDER");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVOPERATOR", Namespace="http://www.digitechsystems.com")]
    public enum PVOPERATOR : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EQUAL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOTEQUAL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GREATERTHAN = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GREATERTHANOREQUAL = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LESSTHAN = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LESSTHANOREQUAL = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISNULL = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISNOTNULL = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LIKE = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOTLIKE = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IN = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOTIN = 11,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVBOOLEAN", Namespace="http://www.digitechsystems.com")]
    public enum PVBOOLEAN : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AND = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OR = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVSORTORDER", Namespace="http://www.digitechsystems.com")]
    public enum PVSORTORDER : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASCENDING = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DESCENDING = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVQUERYTYPE", Namespace="http://www.digitechsystems.com")]
    public enum PVQUERYTYPE : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALLWORDS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANYWORDS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BOOLEAN = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVRESPONSE", Namespace="http://www.digitechsystems.com")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PVEAPIUtility.DocSearchSvc.PVQUERYRESPONSE))]
    public partial class PVRESPONSE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RETURNCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPTIONField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RETURNCODE {
            get {
                return this.RETURNCODEField;
            }
            set {
                if ((this.RETURNCODEField.Equals(value) != true)) {
                    this.RETURNCODEField = value;
                    this.RaisePropertyChanged("RETURNCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DESCRIPTION {
            get {
                return this.DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPTIONField, value) != true)) {
                    this.DESCRIPTIONField = value;
                    this.RaisePropertyChanged("DESCRIPTION");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVQUERYRESPONSE", Namespace="http://www.digitechsystems.com")]
    [System.SerializableAttribute()]
    public partial class PVQUERYRESPONSE : PVEAPIUtility.DocSearchSvc.PVRESPONSE {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PVEAPIUtility.DocSearchSvc.PVPROJECTQUERYRESPONSE[] PROJECTQUERYRESPONSESField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PVEAPIUtility.DocSearchSvc.PVPROJECTQUERYRESPONSE[] PROJECTQUERYRESPONSES {
            get {
                return this.PROJECTQUERYRESPONSESField;
            }
            set {
                if ((object.ReferenceEquals(this.PROJECTQUERYRESPONSESField, value) != true)) {
                    this.PROJECTQUERYRESPONSESField = value;
                    this.RaisePropertyChanged("PROJECTQUERYRESPONSES");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVPROJECTQUERYRESPONSE", Namespace="http://www.digitechsystems.com")]
    [System.SerializableAttribute()]
    public partial class PVPROJECTQUERYRESPONSE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CALLERQUERYIDField;
        
        private long PROJECTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement SEARCHRESULTField;
        
        private int RESULTCOUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPILEDQUERYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAGENEXTKEYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PVEAPIUtility.DocSearchSvc.PVSEARCHSTATISTICS SEARCHSTATISTICSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CALLERQUERYID {
            get {
                return this.CALLERQUERYIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CALLERQUERYIDField, value) != true)) {
                    this.CALLERQUERYIDField = value;
                    this.RaisePropertyChanged("CALLERQUERYID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long PROJECTID {
            get {
                return this.PROJECTIDField;
            }
            set {
                if ((this.PROJECTIDField.Equals(value) != true)) {
                    this.PROJECTIDField = value;
                    this.RaisePropertyChanged("PROJECTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.Linq.XElement SEARCHRESULT {
            get {
                return this.SEARCHRESULTField;
            }
            set {
                if ((object.ReferenceEquals(this.SEARCHRESULTField, value) != true)) {
                    this.SEARCHRESULTField = value;
                    this.RaisePropertyChanged("SEARCHRESULT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int RESULTCOUNT {
            get {
                return this.RESULTCOUNTField;
            }
            set {
                if ((this.RESULTCOUNTField.Equals(value) != true)) {
                    this.RESULTCOUNTField = value;
                    this.RaisePropertyChanged("RESULTCOUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string COMPILEDQUERY {
            get {
                return this.COMPILEDQUERYField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPILEDQUERYField, value) != true)) {
                    this.COMPILEDQUERYField = value;
                    this.RaisePropertyChanged("COMPILEDQUERY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PAGENEXTKEY {
            get {
                return this.PAGENEXTKEYField;
            }
            set {
                if ((object.ReferenceEquals(this.PAGENEXTKEYField, value) != true)) {
                    this.PAGENEXTKEYField = value;
                    this.RaisePropertyChanged("PAGENEXTKEY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public PVEAPIUtility.DocSearchSvc.PVSEARCHSTATISTICS SEARCHSTATISTICS {
            get {
                return this.SEARCHSTATISTICSField;
            }
            set {
                if ((object.ReferenceEquals(this.SEARCHSTATISTICSField, value) != true)) {
                    this.SEARCHSTATISTICSField = value;
                    this.RaisePropertyChanged("SEARCHSTATISTICS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVSEARCHSTATISTICS", Namespace="http://www.digitechsystems.com")]
    [System.SerializableAttribute()]
    public partial class PVSEARCHSTATISTICS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPILEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXECUTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXECUTEFULLTEXTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BUILDRESULTSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TOTALField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string COMPILE {
            get {
                return this.COMPILEField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPILEField, value) != true)) {
                    this.COMPILEField = value;
                    this.RaisePropertyChanged("COMPILE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EXECUTE {
            get {
                return this.EXECUTEField;
            }
            set {
                if ((object.ReferenceEquals(this.EXECUTEField, value) != true)) {
                    this.EXECUTEField = value;
                    this.RaisePropertyChanged("EXECUTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EXECUTEFULLTEXT {
            get {
                return this.EXECUTEFULLTEXTField;
            }
            set {
                if ((object.ReferenceEquals(this.EXECUTEFULLTEXTField, value) != true)) {
                    this.EXECUTEFULLTEXTField = value;
                    this.RaisePropertyChanged("EXECUTEFULLTEXT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BUILDRESULTS {
            get {
                return this.BUILDRESULTSField;
            }
            set {
                if ((object.ReferenceEquals(this.BUILDRESULTSField, value) != true)) {
                    this.BUILDRESULTSField = value;
                    this.RaisePropertyChanged("BUILDRESULTS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TOTAL {
            get {
                return this.TOTALField;
            }
            set {
                if ((object.ReferenceEquals(this.TOTALField, value) != true)) {
                    this.TOTALField = value;
                    this.RaisePropertyChanged("TOTAL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.digitechsystems.com", ConfigurationName="DocSearchSvc.PVDOCUMENTSEARCH")]
    public interface PVDOCUMENTSEARCH {
        
        // CODEGEN: Generating message contract since element name SESSION from namespace http://www.digitechsystems.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.digitechsystems.com/PVDOCUMENTSEARCH/SEARCH", ReplyAction="http://www.digitechsystems.com/PVDOCUMENTSEARCH/SEARCHResponse")]
        PVEAPIUtility.DocSearchSvc.SEARCHResponse SEARCH(PVEAPIUtility.DocSearchSvc.SEARCHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.digitechsystems.com/PVDOCUMENTSEARCH/SEARCH", ReplyAction="http://www.digitechsystems.com/PVDOCUMENTSEARCH/SEARCHResponse")]
        System.Threading.Tasks.Task<PVEAPIUtility.DocSearchSvc.SEARCHResponse> SEARCHAsync(PVEAPIUtility.DocSearchSvc.SEARCHRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SEARCHRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SEARCH", Namespace="http://www.digitechsystems.com", Order=0)]
        public PVEAPIUtility.DocSearchSvc.SEARCHRequestBody Body;
        
        public SEARCHRequest() {
        }
        
        public SEARCHRequest(PVEAPIUtility.DocSearchSvc.SEARCHRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.digitechsystems.com")]
    public partial class SEARCHRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PVEAPIUtility.DocSearchSvc.PVSESSION SESSION;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public PVEAPIUtility.DocSearchSvc.PVQUERY QUERY;
        
        public SEARCHRequestBody() {
        }
        
        public SEARCHRequestBody(PVEAPIUtility.DocSearchSvc.PVSESSION SESSION, PVEAPIUtility.DocSearchSvc.PVQUERY QUERY) {
            this.SESSION = SESSION;
            this.QUERY = QUERY;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SEARCHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SEARCHResponse", Namespace="http://www.digitechsystems.com", Order=0)]
        public PVEAPIUtility.DocSearchSvc.SEARCHResponseBody Body;
        
        public SEARCHResponse() {
        }
        
        public SEARCHResponse(PVEAPIUtility.DocSearchSvc.SEARCHResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.digitechsystems.com")]
    public partial class SEARCHResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PVEAPIUtility.DocSearchSvc.PVQUERYRESPONSE SEARCHResult;
        
        public SEARCHResponseBody() {
        }
        
        public SEARCHResponseBody(PVEAPIUtility.DocSearchSvc.PVQUERYRESPONSE SEARCHResult) {
            this.SEARCHResult = SEARCHResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PVDOCUMENTSEARCHChannel : PVEAPIUtility.DocSearchSvc.PVDOCUMENTSEARCH, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PVDOCUMENTSEARCHClient : System.ServiceModel.ClientBase<PVEAPIUtility.DocSearchSvc.PVDOCUMENTSEARCH>, PVEAPIUtility.DocSearchSvc.PVDOCUMENTSEARCH {
        
        public PVDOCUMENTSEARCHClient() {
        }
        
        public PVDOCUMENTSEARCHClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PVDOCUMENTSEARCHClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PVDOCUMENTSEARCHClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PVDOCUMENTSEARCHClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PVEAPIUtility.DocSearchSvc.SEARCHResponse PVEAPIUtility.DocSearchSvc.PVDOCUMENTSEARCH.SEARCH(PVEAPIUtility.DocSearchSvc.SEARCHRequest request) {
            return base.Channel.SEARCH(request);
        }
        
        public PVEAPIUtility.DocSearchSvc.PVQUERYRESPONSE SEARCH(PVEAPIUtility.DocSearchSvc.PVSESSION SESSION, PVEAPIUtility.DocSearchSvc.PVQUERY QUERY) {
            PVEAPIUtility.DocSearchSvc.SEARCHRequest inValue = new PVEAPIUtility.DocSearchSvc.SEARCHRequest();
            inValue.Body = new PVEAPIUtility.DocSearchSvc.SEARCHRequestBody();
            inValue.Body.SESSION = SESSION;
            inValue.Body.QUERY = QUERY;
            PVEAPIUtility.DocSearchSvc.SEARCHResponse retVal = ((PVEAPIUtility.DocSearchSvc.PVDOCUMENTSEARCH)(this)).SEARCH(inValue);
            return retVal.Body.SEARCHResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PVEAPIUtility.DocSearchSvc.SEARCHResponse> PVEAPIUtility.DocSearchSvc.PVDOCUMENTSEARCH.SEARCHAsync(PVEAPIUtility.DocSearchSvc.SEARCHRequest request) {
            return base.Channel.SEARCHAsync(request);
        }
        
        public System.Threading.Tasks.Task<PVEAPIUtility.DocSearchSvc.SEARCHResponse> SEARCHAsync(PVEAPIUtility.DocSearchSvc.PVSESSION SESSION, PVEAPIUtility.DocSearchSvc.PVQUERY QUERY) {
            PVEAPIUtility.DocSearchSvc.SEARCHRequest inValue = new PVEAPIUtility.DocSearchSvc.SEARCHRequest();
            inValue.Body = new PVEAPIUtility.DocSearchSvc.SEARCHRequestBody();
            inValue.Body.SESSION = SESSION;
            inValue.Body.QUERY = QUERY;
            return ((PVEAPIUtility.DocSearchSvc.PVDOCUMENTSEARCH)(this)).SEARCHAsync(inValue);
        }
    }
}
